name: "Podcast Generator"
author: "Karl Castillo"
description: "Generates a podcast RSS feed"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email: 
    description: "The committer's email address (default is '${{ github.actor }}@localhost', which may not be a valid email address for all users)"
    required: true
    default: "${{ github.actor }}@localhost"
  name:
    description: "The commiter's name (default is the GitHub actor's username)"
    required: true
    default: "${{ github.actor }}"